<?php
echo 'var profiles;';
echo 'var loc = window.location.pathname;';
echo 'loc = loc.substring(0, loc.lastIndexOf("/"));';
echo 'var dir = loc.substring(loc.lastIndexOf("/")+1);';
echo 'var url = "https://facilino.webs.upv.es/profiles.php";';
echo '$.ajax({ url: url, dataType: "text",async: false, }).done(function(text) { profiles=$.parseJSON(text) });';
echo 'var options = {zoom: 1, profiles: profiles};';
echo 'Facilino.load(options);';
echo 'FacilinoFunctions.load(options);';
echo 'FacilinoControls.load(options);';
echo 'FacilinoProgramming.load(options);';
echo 'FacilinoInterrupts.load(options);';
echo 'FacilinoStateMachine.load(options);';
echo 'FacilinoLogic.load(options);';
echo 'FacilinoBitwise.load(options);';
echo 'FacilinoMaths.load(options);';
echo 'FacilinoArrays.load(options);';
echo 'FacilinoCurves.load(options);';
echo 'FacilinoVariables.load(options);';
echo 'FacilinoVariablesArray.load(options);';
echo 'FacilinoEEPROM.load(options);';
echo 'FacilinoText.load(options);';
echo 'FacilinoInOut.load(options);';
echo 'FacilinoButtons.load(options);';
echo 'FacilinoBus.load(options);';
echo 'FacilinoInOutOthers.load(options);';
echo 'FacilinoLCD.load(options);';
echo 'FacilinoLEDMatrix.load(options);';
echo 'FacilinoLEDStrip.load(options);';
echo 'FacilinoOLED.load(options);';
echo 'FacilinoTFT.load(options);';
echo 'FacilinoSerial.load(options);';
echo 'FacilinoBluetooth.load(options);';
echo 'FacilinoBLE.load(options);';
echo 'FacilinoWiFi.load(options);';
echo 'FacilinoHTTP.load(options);';
echo 'FacilinoIoT.load(options);';
echo 'FacilinoIR.load(options);';
echo 'FacilinoSonar.load(options);';
echo 'FacilinoInfraRed.load(options);';
echo 'FacilinoColor.load(options);';
echo 'FacilinoLDR.load(options);';
echo 'FacilinoLightDimmer.load(options);';
echo 'FacilinoBuzzer.load(options);';
echo 'FacilinoMic.load(options);';
echo 'FacilinoMelody.load(options);';
echo 'FacilinoMP3.load(options);';
echo 'FacilinoMotor.load(options);';
echo 'FacilinoRobotBase.load(options);';
echo 'FacilinoRobotAcc.load(options);';
echo 'FacilinoRobotWalk.load(options);';
echo 'FacilinoRobotMeArm.load(options);';
echo 'FacilinoController.load(options);';
echo 'FacilinoFilter.load(options);';
echo 'FacilinoTemperature.load(options);';
echo 'FacilinoHumidity.load(options);';
echo 'FacilinoRain.load(options);';
echo 'FacilinoGas.load(options);';
echo 'FacilinoAmbientMiscellaneous.load(options);';
echo 'FacilinoHTML.load(options);';
echo 'FacilinoESPUI.load(options);';
?>